version: "3.9"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=RSController
      - POSTGRES_PASSWORD=abc12345
    ports:
      - "5432:5432"
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - elastic
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
  logstash:
    container_name: logstash-container
    build:
      context: Logstash
      dockerfile: Dockerfile
    networks:
      - clients
      - elastic
    depends_on:
      - elasticsearch
    ports:
      - "5000:5000"
      - "9600:9600"
  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:7.11.0
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - elastic
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

networks:
  elastic:
    driver: bridge
  clients:
    driver: bridge
    external: true

volumes:
  elasticsearch-data:
    driver: local
